name: Build and push nuget

'on':
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-push-nuget:
    permissions:
      contents: read

    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "IIIF.sln"
      DOTNET_VERSION: "8.0.x"

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/IIIF

    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: "6.x"

      - name: Determine GitVersion
        uses: gittools/actions/gitversion/execute@v4

      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore -p:ContinuousIntegrationBuild=true

      - name: Test
        run: dotnet test $SOLUTION /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Pack
        run: dotnet pack IIIF/IIIF.csproj --configuration $BUILD_CONFIG -p:Version=$GITVERSION_NUGETVERSION --no-restore --no-build

      - name: Publish Package and Symbols
        if: startsWith(github.ref, 'refs/tags/v')
        run: dotnet nuget push '**/*.nupkg' --source 'https://api.nuget.org/v3/index.json' --api-key ${{secrets.NUGET_API_KEY}}